import type { Entry } from "$lib/bridge/types";

const mockEntries: Entry[] = [
  {
    id: "1",
    type: "login",
    title: "GitHub",
    subtitle: "erickgnavar",
    url: "github.com",
    username: "erickgnavar",
    password: "ghp_GitHubPersonalToken2026!",
    totp: "otpauth://totp/GitHub:erickgnavar?secret=JBSWY3DPEHPK3PXP&issuer=GitHub&algorithm=SHA1&digits=6&period=30",
    notes:
      "Personal GitHub account with TOTP enabled. Has access to all personal repos and organizations.",
    tags: ["work", "dev"],
    favorite: true,
    iconHint: "github",
    attachments: [{ id: "a1", name: "backup_codes.txt", sizeBytes: 1240 }],
    customFields: [{ name: "API Token", value: "ghp_api_token_value", protected: true }],
    modifiedAt: "2026-06-25T14:30:00Z",
    createdAt: "2024-01-15T10:00:00Z",
    historyCount: 3,
  },
  {
    id: "2",
    type: "login",
    title: "Stripe Dashboard",
    subtitle: "admin@ruaylabs.com",
    url: "dashboard.stripe.com",
    username: "admin@ruaylabs.com",
    password: "sk_live_StripeProdKey2026",
    notes: "Production Stripe account. Do not share this password with anyone outside the team.",
    tags: ["work", "critical"],
    favorite: true,
    iconHint: "stripe",
    attachments: [],
    customFields: [{ name: "Publishable Key", value: "pk_live_stripe_pub_key", protected: false }],
    modifiedAt: "2026-06-22T09:15:00Z",
    createdAt: "2024-03-20T08:00:00Z",
    historyCount: 1,
  },
  {
    id: "3",
    type: "login",
    title: "Anthropic Console",
    subtitle: "erick@ruaylabs.com",
    url: "console.anthropic.com",
    username: "erick@ruaylabs.com",
    password: "AnthropicClaudeKey2026!",
    notes: "Anthropic API access. API keys are in custom fields.",
    tags: ["work", "ai"],
    favorite: false,
    iconHint: "anthropic",
    attachments: [],
    customFields: [{ name: "API Key", value: "sk-ant-api-key-value", protected: true }],
    modifiedAt: "2026-06-20T16:45:00Z",
    createdAt: "2024-05-10T12:00:00Z",
    historyCount: 2,
  },
  {
    id: "4",
    type: "login",
    title: "Cloudflare",
    subtitle: "erick@ruaylabs.com",
    url: "dash.cloudflare.com",
    username: "erick@ruaylabs.com",
    password: "CF_GlobalAPIKey2026",
    totp: "otpauth://totp/Cloudflare:erick@ruaylabs.com?secret=ABCDEFGHIJKLMNOP&issuer=Cloudflare&algorithm=SHA1&digits=6&period=30",
    notes: "Cloudflare dashboard with multiple domains managed.",
    tags: ["work", "infra"],
    favorite: false,
    iconHint: "cloudflare",
    attachments: [],
    customFields: [{ name: "API Token", value: "cf_api_token_value", protected: true }],
    modifiedAt: "2026-06-18T11:30:00Z",
    createdAt: "2024-02-01T09:00:00Z",
    historyCount: 5,
  },
  {
    id: "5",
    type: "login",
    title: "Hetzner Cloud",
    subtitle: "eric gnava",
    url: "console.hetzner.cloud",
    username: "eric gnava",
    password: "HetznerCloudPass2026!",
    notes: "Hetzner cloud console for server management.",
    tags: ["homelab", "infra"],
    favorite: true,
    iconHint: "hetzner",
    attachments: [],
    customFields: [],
    modifiedAt: "2026-06-15T08:20:00Z",
    createdAt: "2024-06-01T14:00:00Z",
    historyCount: 1,
  },
  {
    id: "6",
    type: "login",
    title: "Tailscale Admin",
    subtitle: "erick@ruaylabs.com",
    url: "login.tailscale.com",
    username: "erick@ruaylabs.com",
    password: "TS_AuthKey2026",
    notes: "Tailscale admin console. Used for the homelab mesh network.",
    tags: ["homelab", "dev"],
    favorite: false,
    iconHint: "tailscale",
    attachments: [],
    customFields: [],
    modifiedAt: "2026-06-10T19:00:00Z",
    createdAt: "2024-07-15T11:00:00Z",
    historyCount: 0,
  },
  {
    id: "7",
    type: "login",
    title: "Forgejo",
    subtitle: "erick",
    url: "git.ruaylabs.com",
    username: "erick",
    password: "ForgejoPersonalToken2026",
    notes: "Self-hosted Forgejo instance at git.ruaylabs.com.",
    tags: ["homelab", "dev"],
    favorite: false,
    iconHint: "forgejo",
    attachments: [],
    customFields: [],
    modifiedAt: "2026-06-08T14:10:00Z",
    createdAt: "2024-08-20T16:00:00Z",
    historyCount: 0,
  },
  {
    id: "8",
    type: "note",
    title: "Wi-Fi Credentials",
    subtitle: "",
    notes:
      "Home network:\nSSID: Ruaylabs-5G\nPassword: HomeWiFiPass2026!\n\nGuest network:\nSSID: Ruaylabs-Guest\nPassword: GuestPass2026!",
    tags: ["homelab"],
    favorite: false,
    iconHint: "",
    attachments: [],
    customFields: [],
    modifiedAt: "2026-06-01T10:00:00Z",
    createdAt: "2024-01-10T09:00:00Z",
    historyCount: 2,
  },
  {
    id: "9",
    type: "identity",
    title: "Erick Gnavar",
    subtitle: "Personal Identity",
    identity: {
      firstName: "Erick",
      lastName: "Gnavar",
      email: "erick@ruaylabs.com",
      phone: "+1-555-0123",
      address: "123 Main St, San Francisco, CA 94102",
    },
    tags: ["personal"],
    favorite: false,
    iconHint: "",
    attachments: [],
    customFields: [],
    modifiedAt: "2026-05-20T12:00:00Z",
    createdAt: "2024-01-01T08:00:00Z",
    historyCount: 1,
  },
  {
    id: "10",
    type: "card",
    title: "Visa •••• 4242",
    subtitle: "Erick Gnavar",
    card: {
      holder: "Erick Gnavar",
      number: "4111111111114242",
      brand: "Visa",
      expMonth: 12,
      expYear: 2028,
      cvv: "123",
    },
    tags: ["personal", "critical"],
    favorite: false,
    iconHint: "",
    attachments: [],
    customFields: [],
    modifiedAt: "2026-04-15T09:00:00Z",
    createdAt: "2024-02-14T10:00:00Z",
    historyCount: 0,
  },
  {
    id: "11",
    type: "login",
    title: "AWS Console",
    subtitle: "admin@ruaylabs.com",
    url: "aws.amazon.com/console",
    username: "admin@ruaylabs.com",
    password: "AWS_RootPassword2026!",
    notes: "AWS root account. MFA is enforced via hardware key.",
    tags: ["work", "critical"],
    favorite: true,
    iconHint: "",
    attachments: [],
    customFields: [
      { name: "Account ID", value: "123456789012", protected: false },
      { name: "IAM User", value: "admin", protected: false },
    ],
    modifiedAt: "2026-06-27T07:00:00Z",
    createdAt: "2024-01-05T08:00:00Z",
    historyCount: 4,
  },
  {
    id: "12",
    type: "login",
    title: "Discord",
    subtitle: "erickgnavar",
    url: "discord.com",
    username: "erickgnavar",
    password: "DiscordPass2026!",
    notes: "Personal Discord account.",
    tags: ["personal"],
    favorite: false,
    iconHint: "",
    attachments: [],
    customFields: [],
    modifiedAt: "2026-03-10T18:30:00Z",
    createdAt: "2024-09-01T15:00:00Z",
    historyCount: 0,
  },
];

let vaultMeta = $state<{ path: string; name: string; itemCount: number } | null>(null);
let entries = $state<Entry[]>(mockEntries);

export const vault = {
  get entries() {
    return entries;
  },
  get meta() {
    return vaultMeta;
  },
  setMeta(m: { path: string; name: string; itemCount: number } | null) {
    vaultMeta = m;
  },
  getEntry(id: string): Entry | undefined {
    return entries.find((e) => e.id === id);
  },
  setEntries(data: Entry[]) {
    entries = data;
  },
};
